import { useState } from "react";
import { T } from "../theme";
import { AffLink } from "../shared";

type FAQItem = { q: string; a: string; links: { label: string; url: string }[] };
type FAQCategory = { category: string; questions: FAQItem[] };

const FAQ_DATA: FAQCategory[] = [
  { category: "Wearing it right", questions: [
    { q: "Which buttons do I fasten on a single-breasted two-button jacket?", a: "The top button only. Always. The bottom button on a two-button jacket is never fastened — this is one of the oldest rules in menswear and dates back to King Edward VII. Fastening the bottom button makes the jacket pull, bunch at the waist, and look like it does not fit. When you sit down, unbutton the top button. When you stand, fasten it again.", links: [] },
    { q: "What about a single-breasted three-button jacket?", a: "The middle button always, the top button sometimes, the bottom button never. The most common approach is to fasten only the middle button, which gives a clean line. Some grooms fasten the top and middle together for a more formal look. The bottom button follows the same rule as always — never fastened.", links: [] },
    { q: "What about a single-breasted one-button jacket?", a: "Fasten it when standing, unfasten it when sitting. Simple. A one-button jacket is very clean and modern — the single button sits at the natural waist and the whole line of the jacket depends on it being done up correctly when you are on your feet.", links: [] },
    { q: "How do I wear a double-breasted jacket?", a: "Always fully fastened — both functional buttons done up whenever you are wearing it. Unlike single-breasted, a double-breasted jacket should stay buttoned even when sitting. The overlap of the front panels is structural — an unfastened double-breasted jacket looks deliberately undone rather than casually relaxed. The exception is when you remove it entirely.", links: [] },
    { q: "Does wearing a waistcoat change the button rules?", a: "Yes. When you are wearing a waistcoat, you leave the jacket completely unbuttoned. The waistcoat covers the shirt and waist, so the jacket button serves no functional or visual purpose. Buttoning your jacket over a waistcoat creates bulk and ruins the line of both garments. Jacket open, waistcoat fastened — that is the correct three-piece look.", links: [] },
    { q: "Which buttons do I fasten on a waistcoat?", a: "All of them except the bottom one. The bottom button of a waistcoat is left undone — the same principle as a single-breasted suit jacket. This allows movement, prevents the waistcoat from pulling when you sit, and is simply the correct way to wear one. If your waistcoat has five buttons, fasten the top four. If it has three buttons, fasten the top two.", links: [] },
    { q: "How should a suit jacket fit?", a: "The shoulder seam should sit exactly at the end of your shoulder — not hanging over the arm, not pulling inward. The collar should lie flat against your shirt collar with no gap. The jacket should button without pulling across the chest. The sleeve should show approximately 1-1.5cm of shirt cuff below the jacket sleeve. The jacket length should cover your seat. If any of these are wrong, ask for alterations — most hire companies include basic alterations in the price.", links: [{ label: "Book a fitting at Moss Bros", url: "https://www.mossbros.co.uk/suit-hire" }, { label: "Book at Savoy Taylors Guild", url: "https://www.savoytaylorsguild.co.uk/hire/morning-suits" }] },
    { q: "How much shirt cuff should show below the jacket sleeve?", a: "Approximately 1 to 1.5 centimetres. This is called the shirt cuff break. It is one of the most noticeable details in close-up photographs and at the ceremony. Too much cuff looks like the jacket is too short. No cuff showing looks like the jacket is too long or the shirt is too short. If your cuffs are not showing, ask the hire shop or tailor to shorten the jacket sleeve.", links: [] },
    { q: "How should trousers fit and sit?", a: "Trousers should sit at the natural waist — not on the hips. The break at the hem should be slight, with the trouser just grazing the top of the shoe. Too much break creates a bunching of fabric at the ankle that looks sloppy. No break at all looks very fashion-forward and works with slim modern suits. If you have turn-ups, they add weight to the hem and help it sit correctly.", links: [] },
    { q: "Should I wear a belt or side adjusters?", a: "Side adjusters for formal wear, always. A belt with a formal suit is technically incorrect — belts are workwear and casual wear. A well-fitted suit with side adjusters looks cleaner, sits better, and is simply the more elegant choice. If your trousers only have belt loops, a plain leather belt in black or dark brown is fine, but avoid anything with a prominent buckle.", links: [] },
    { q: "How do I wear a pocket square correctly?", a: "It should look intentional but not overworked. The flat presidential fold — a clean straight edge of fabric just visible above the pocket — works for every suit and every occasion. It takes about 30 seconds to do and never looks wrong. Avoid over-engineered multi-point folds that look like origami. The pocket square should complement the tie or buttonhole, not match it exactly — same colour family, not identical fabric.", links: [] },
    { q: "Should the pocket square match the tie?", a: "No — and this is a common mistake. Matching your pocket square exactly to your tie looks like you bought them as a set, which reads as an effort to coordinate rather than actual style. The pocket square should be in the same colour family or complement the tie without being identical. A classic approach is a white pocket square with any coloured tie — it always works.", links: [] },
    { q: "How do I wear a buttonhole correctly?", a: "The buttonhole goes through the buttonhole on the left lapel — there is a small loop of thread on the back of most jacket lapels specifically for this. The stem should sit vertically and the flower should face outward. Secure it with the pin if provided. It should sit flat against the lapel without drooping. Pick it up on the morning of the wedding, not the day before.", links: [] },
    { q: "When do I take my jacket off?", a: "Traditionally the groom removes his jacket first, giving everyone else permission to do the same. Most grooms keep their jacket on for the ceremony, the drinks reception, and the meal, then remove it for the evening. It is your day — if it is August and 28 degrees, remove it whenever you want. Just do it before everyone else starts quietly dying of heat.", links: [] },
    { q: "How should I tie a half Windsor knot?", a: "The half Windsor produces a medium-sized, neat triangular knot that works with most collar types. Start with the wide end on your right, roughly 30cm lower than the narrow end. Cross the wide end over the narrow end. Bring it up through the neck loop. Wrap it around the front of the narrow end from right to left. Bring it up through the neck loop again. Pass it down through the front loop you just created. Tighten gently and slide up to the collar. The point of the tie should reach your belt buckle.", links: [{ label: "Visual guide on Ties.com", url: "https://www.ties.com/how-to-tie-a-tie/half-windsor" }] },
    { q: "How should I tie a full Windsor knot?", a: "The full Windsor produces a large, wide, symmetrical knot. It requires a spread collar to sit correctly — a narrow collar will look overwhelmed by the knot. Start with the wide end about 40cm lower than the narrow end. Cross wide over narrow. Bring up through neck loop and down to the right. Wrap around the front to the left, then up through the neck loop, then right, then up through the neck loop again. Pass down through the front loop. Tighten and centre. It should fill a spread collar perfectly.", links: [{ label: "Visual guide on Ties.com", url: "https://www.ties.com/how-to-tie-a-tie/windsor" }] },
    { q: "How do I tie a bow tie?", a: "Put the bow tie around your neck with the right side about 3cm longer than the left. Cross the longer end over the shorter end and up through the neck loop — like the first step of tying your shoelaces. Fold the shorter end horizontally to form the front bow shape. Drop the longer end over the centre of this bow. Fold the longer end and push it through the loop behind the front bow. Tighten by pulling both folded ends gently outward. Adjust the symmetry — it should look slightly imperfect, not machine-perfect. Watch a YouTube video the week before, practise twice, and it will take you under a minute on the day.", links: [{ label: "How to tie a bow tie on realmenrealstyle.com", url: "https://www.realmenrealstyle.com/tie-bow-tie/" }] },
    { q: "What is the correct way to wear a cummerbund?", a: "A cummerbund is a wide pleated sash worn around the waist in place of a waistcoat. It covers the trouser waistband and the shirt above it. The single most important rule: pleats face upward. This is one of the most commonly got wrong details in black tie — if the pleats face downward it is immediately noticeable to anyone who knows black tie. The cummerbund should sit snugly at the natural waist, covering the trouser waistband completely. Match it to your bow tie — both in black silk for classic black tie, or both in midnight blue if your tuxedo is midnight blue. Remove it when you remove your jacket.", links: [{ label: "Browse black tie accessories at Hawes and Curtis", url: "https://www.hawesandcurtis.co.uk/mens/black-tie" }] },
    { q: "Should my socks match my trousers or my shoes?", a: "Your trousers. The logic is that socks are a visual extension of the trouser leg — when you cross your legs or walk up stairs, you want the trouser and sock to read as one continuous line down to the shoe. A dark navy suit with dark navy socks and black shoes looks intentional. Dark navy suit with white sports socks is genuinely one of the most common mistakes grooms make on the day.", links: [] },
    { q: "Do I need to break in new shoes before the wedding?", a: "Yes. New leather shoes, particularly quality ones from Loake or Cheaney, need wearing in before the day. Wear them around the house for a few evenings and on at least one full day out before the wedding. Arriving at your ceremony in brand new shoes that have never been worn is a reliable way to spend the entire day in pain. If you are hiring shoes, this is less of an issue but still worth a short wear beforehand.", links: [{ label: "Browse Loake shoes", url: "https://www.loake.co.uk/collections/oxford-shoes" }] },
    { q: "How do I care for my suit on the morning of the wedding?", a: "Hang it up the night before, never leave it folded. If it has any creases, hang it in the bathroom while you shower — the steam will relax most of them without touching it. If you need to press it, use a pressing cloth between the iron and the fabric to avoid shine marks. Check all buttons are secure. Check the pockets are empty. Put the buttonhole in last, just before you leave.", links: [] },
  ]},
  { category: "Attire", questions: [
    { q: "Do my groomsmen have to match?", a: "No. Coordinated is fine — same colour with slight variations in lapel or neckwear is more interesting than identical suits.", links: [] },
    { q: "Who pays for the groomsmen suits?", a: "Traditionally the groom pays for groomsmen hire. If you are asking them to hire specifically for your wedding, covering the cost is a nice gesture. Many grooms ask groomsmen to buy their own if they are purchasing to keep.", links: [{ label: "Hire at Moss Bros", url: "https://www.mossbros.co.uk/hire" }] },
    { q: "How far in advance should I book a suit hire?", a: "At least 3-4 months. Six months is better for a large party. Fittings typically happen 6-8 weeks out with collection a week before. Do not leave it later than 6 weeks.", links: [{ label: "Book at Moss Bros", url: "https://www.mossbros.co.uk/hire" }, { label: "Book at Savoy Taylors Guild", url: "https://www.savoytaylorsguild.co.uk/hire/morning-suits" }] },
    { q: "What is the difference between a notched and a peak lapel?", a: "A notched lapel has a small V-shaped cutout where the collar meets the lapel — the most common style. A peak lapel has points that angle upward toward the shoulders, giving a more formal and assertive look. Most grooms choose peak to stand out from their groomsmen.", links: [] },
    { q: "Should my shoes match my groomsmen?", a: "They do not need to match exactly, but should be in the same family. A similar colour and formality level is enough.", links: [{ label: "Shop at Loake", url: "https://www.loake.co.uk/collections/oxford-shoes" }, { label: "Shop at Cheaney", url: "https://www.cheaney.co.uk/collections/mens-oxford-shoes" }] },
    { q: "Do I need a buttonhole?", a: "Not strictly, but they are worth having. A buttonhole costs around £10-15 from your florist, coordinates with the bouquet, and genuinely elevates the look.", links: [] },
    { q: "What is the difference between pocket styles?", a: "Flap pockets have a fabric flap over the opening — the standard casual style. Jetted pockets have no flap, just a clean slit, and are more formal — correct for black tie. Patch pockets are visible stitched pockets sewn onto the outside of the jacket, more casual and common on linen or summer suits. A ticket pocket is a small extra pocket above the right hip pocket — a very British detail that adds a considered touch to a formal suit.", links: [] },
    { q: "What colour suit works best for an outdoor summer wedding?", a: "Lighter greys, mid-blue, or stone work well in summer. Avoid heavy charcoal or black in direct sunlight. Navy is versatile and works in almost any light.", links: [{ label: "Browse at Charles Tyrwhitt", url: "https://www.ctshirts.com/suits?colour=navy" }] },
    { q: "Should I buy or hire?", a: "Hire if you are unlikely to wear a formal suit again. Buy if you wear suits for work or events regularly. A good off-the-peg suit from Next or Ted Baker at £300-£450 is often better value than hire over time.", links: [{ label: "Browse at Next", url: "https://www.next.co.uk/shop/gender-men/category-suits" }, { label: "Browse at Ted Baker", url: "https://www.tedbaker.com/uk/mens/category/suits" }] },
  ]},
  { category: "Rings", questions: [
    { q: "Do I actually need to wear a wedding ring?", a: "No. It is a personal choice. Some grooms do not wear jewellery, have jobs where rings are impractical, or simply prefer not to. Worth discussing with your partner beforehand rather than surprising them on the day.", links: [] },
    { q: "Who buys the groom's wedding ring?", a: "Traditionally the bride's family bought the groom's ring. In practice, most couples simply buy both rings together.", links: [] },
    { q: "Should my ring match her engagement ring?", a: "It does not have to, but it is worth thinking about. If her ring is platinum or white gold, wearing yellow gold will create a contrast that some couples love and others find jarring.", links: [{ label: "Browse at Beaverbrooks", url: "https://www.beaverbrooks.co.uk/mens/wedding-rings" }] },
    { q: "Can I get my ring resized after the wedding?", a: "Most metals can be resized. Gold and platinum can be resized relatively easily. Tungsten, titanium, and carbon fibre cannot be resized at all — if your finger changes size, you would need a new ring.", links: [] },
    { q: "What is the difference between platinum and white gold?", a: "Platinum is naturally white and stays white permanently — it never needs replating. White gold is yellow gold coated in rhodium, which wears off over time and needs replating every few years at a cost of around £40-80.", links: [] },
    { q: "Does a hammered finish hide scratches?", a: "Yes, significantly. A hammered or matte finish masks everyday wear far better than a polished finish. If you work with your hands or are hard on jewellery, matte or hammered is a practical as well as stylistic choice.", links: [{ label: "Browse hammered rings on Etsy UK", url: "https://www.etsy.com/uk/search?q=hammered+mens+wedding+ring" }] },
    { q: "How do I measure my ring size at home?", a: "Wrap a thin strip of paper around your finger, mark where it overlaps, measure the length in millimetres, and divide by 3.14 to get the diameter. Take the measurement to any jeweller to match to UK sizing.", links: [{ label: "F.Hinds ring size guide", url: "https://www.fhinds.co.uk/help/ring-size-guide" }] },
    { q: "What is silicone / rubber ring?", a: "A soft, flexible ring made from silicone. Increasingly popular for grooms who work with their hands, in healthcare, or do a lot of sport. Cannot catch on machinery. Many grooms buy a silicone ring for work and a metal ring for everyday wear.", links: [{ label: "Browse on Amazon UK", url: "https://www.amazon.co.uk/s?k=silicone+wedding+ring+mens" }] },
    { q: "What about a ring tattoo?", a: "A ring tattoo is a permanent design inked on the ring finger. Zero cost after the tattooing, impossible to lose, completely personal. The design can be anything from a simple band to an intricate pattern. Research your artist carefully — quality varies enormously.", links: [{ label: "Find artists on Tattoodo", url: "https://www.tattoodo.com/find?type=tattoo&q=ring+tattoo" }] },
  ]},
  { category: "Stag", questions: [
    { q: "Who organises the stag do?", a: "The best man, traditionally. He plans it, coordinates the group, collects deposits, and manages all the details. The groom's job is to show up.", links: [] },
    { q: "Who pays for the stag do?", a: "Each person pays their own way, including the groom in most cases. Traditionally the group covered the groom's share, but this is less common now particularly for longer trips.", links: [] },
    { q: "How far in advance should I book?", a: "At least 3-4 months for UK trips, 4-6 months for European travel. Popular Krakow stag packages sell out in summer months. The bigger the group, the earlier you need to start.", links: [{ label: "Search flights on Skyscanner", url: "https://www.skyscanner.net/flights/gb/anywhere/" }] },
    { q: "What if someone in the group cannot afford it?", a: "Either choose a destination and budget that works for everyone, or have a frank conversation with that person privately. Do not put social pressure on people to spend money they do not have.", links: [] },
    { q: "Should I invite my dad to the stag?", a: "Only if he would genuinely enjoy it and fit in with the group. A split stag — a dinner or afternoon with family, then a separate evening with the core group — is increasingly common and works well.", links: [] },
    { q: "Is Krakow still worth it?", a: "Yes. It remains the best value European stag destination. Flights are cheap, everything is cheap, and the bars genuinely welcome stag groups.", links: [{ label: "Flights to Krakow on Skyscanner", url: "https://www.skyscanner.net/flights/gb/anywhere/" }] },
    { q: "Do I need travel insurance for a European stag?", a: "Yes. A standard single-trip policy costs around £10-20 per person and covers medical emergencies, cancellations, and lost luggage.", links: [{ label: "Compare on Compare the Market", url: "https://www.comparethemarket.com/travel-insurance/single-trip/" }] },
    { q: "What if someone drops out after paying?", a: "Anyone who drops out should still contribute to fixed costs — accommodation and activities that were booked on their behalf. Agree this up front and the best man should collect deposits before booking anything.", links: [] },
  ]},
  { category: "Speech", questions: [
    { q: "When does the groom give his speech?", a: "At a UK wedding, the traditional order is: father of the bride, groom, best man. The groom speaks second.", links: [] },
    { q: "How long should the groom's speech be?", a: "4-5 minutes is ideal. At 130 words per minute, aim for 520-650 words. Most grooms write too much — cut ruthlessly.", links: [] },
    { q: "Can I use notes?", a: "Yes. A small card is fine and most guests will never notice. If you use your phone, keep the screen bright and turn off notifications.", links: [] },
    { q: "What should I actually say about my wife?", a: "One specific story or moment — not a list of qualities. The moment you knew is more powerful than any description.", links: [] },
    { q: "How do I deal with nerves before the speech?", a: "Practise until you know it well enough to look up from your notes. Eat something beforehand. One drink is fine; more is not. The nerves are almost never visible from the room.", links: [] },
    { q: "Should I mention ex-partners in the speech?", a: "No. There is no version of this that works.", links: [] },
    { q: "Do I have to thank everyone?", a: "You should thank both sets of parents, your partner, and the groomsmen. Beyond that is optional. Avoid reading out a long list of names — guests switch off.", links: [] },
    { q: "What is the order of toasts?", a: "The groom traditionally toasts the bridesmaids at the end of his speech. The best man then responds on behalf of the bridesmaids and toasts the couple. The father of the bride typically opens by toasting the couple.", links: [] },
  ]},
  { category: "On the day", questions: [
    { q: "What time should I arrive at the venue?", a: "At least 45 minutes before the ceremony start time. This gives you time to greet arriving guests, sort any last-minute details with the venue, and settle your nerves.", links: [] },
    { q: "What do I do on the morning of the wedding?", a: "Eat a proper breakfast. Have a clear plan for getting ready with your groomsmen. Confirm timings with the best man the night before. Leave more time than you think you need.", links: [] },
    { q: "Should I eat before the ceremony?", a: "Yes. Definitely. Nerves and an empty stomach are a bad combination. You may not eat again until the wedding breakfast several hours later.", links: [] },
    { q: "Can I see my partner before the ceremony?", a: "Traditionally no, but a first look — a private moment together before the ceremony — is increasingly common and often results in better, more relaxed photographs.", links: [] },
    { q: "How much cash should I have on the day?", a: "Enough to cover supplier gratuities if you are giving them. Work out who you want to tip, put each in a named envelope, and give them to the best man to distribute.", links: [] },
    { q: "What do I do during the couple portraits?", a: "This is your only window to eat, drink, and decompress between the ceremony and the reception. Do not let your photographer rush you — have a drink, eat something, see your family.", links: [] },
  ]},
  { category: "Money & etiquette", questions: [
    { q: "Who pays for what at a UK wedding traditionally?", a: "Traditionally the bride's family paid for most of the wedding, the groom paid for the honeymoon and rings. In practice most modern couples split costs between themselves and contributions from both families.", links: [] },
    { q: "Do I need to tip wedding suppliers in the UK?", a: "Tipping is not expected in the UK the way it is in some other countries, but it is a widely appreciated gesture for good service. It is entirely optional. Cash in envelopes given at the end of the day is the standard approach.", links: [] },
    { q: "How much should I tip the photographer?", a: "There is no set amount. If you want to tip, £50-100 for a solo photographer or £100-200 for a two-person team is generous and appreciated.", links: [] },
    { q: "How much should I tip the band or DJ?", a: "Optional. £50-100 for a DJ, £100-200 for a band is typical if you want to show appreciation.", links: [] },
    { q: "Should I give my groomsmen a gift?", a: "It is a nice gesture but not required. Something personal and practical works better than generic engraved hip flasks.", links: [{ label: "Browse at Not On The High Street", url: "https://www.notonthehighstreet.com/personalisedgifts/for-him" }, { label: "Browse personalised gifts at Etsy UK", url: "https://www.etsy.com/uk" }] },
    { q: "What is an appropriate groomsmen gift budget?", a: "£30-75 per groomsman is typical. More for a best man who has done a lot. Quality matters more than price.", links: [] },
    { q: "Should I write personal thank you cards?", a: "Yes. Handwritten cards to parents, bridal party, and close friends who contributed meaningfully are genuinely appreciated and increasingly rare. Aim to send them within 3 weeks of the wedding.", links: [{ label: "Browse cards at Papier", url: "https://www.papier.com/thank-you-cards" }] },
  ]},
  { category: "Honeymoon", questions: [
    { q: "Who plans the honeymoon?", a: "Traditionally the groom planned and paid for the honeymoon as a surprise. In practice most couples plan it together. A surprise honeymoon requires knowing your partner well enough to get the destination, climate, and style right.", links: [{ label: "Browse packages on Kuoni", url: "https://www.kuoni.co.uk/honeymoons" }, { label: "Browse on Mr and Mrs Smith", url: "https://www.mrandmrssmith.com/romantic-hotels" }] },
    { q: "How soon after the wedding should the honeymoon be?", a: "Most couples go within a week of the wedding. Some take a mini-moon immediately and a longer trip later. There is no correct answer.", links: [] },
    { q: "Do I need to change my name on my passport before the honeymoon?", a: "Only if your partner is changing her name before you travel. All bookings must match your current passport name exactly.", links: [] },
    { q: "Should I tell the hotel it is our honeymoon?", a: "Yes. Most hotels will do something to mark the occasion — room upgrade, champagne, flowers, or a note. There is no downside to mentioning it when booking and again at check-in.", links: [] },
  ]},
  { category: "Traditions", questions: [
    { q: "Do the groom and best man greet guests on arrival?", a: "Traditionally yes — the groom and groomsmen welcome arriving guests before the ceremony. This is a warm gesture but not a strict requirement. It helps guests feel welcomed and gives you something to do while waiting.", links: [] },
    { q: "Does the suit jacket stay on until the groom removes his?", a: "Yes — this is a traditional convention. The groom removes his jacket first, giving permission for everyone else to do the same. Most grooms remove theirs after the wedding breakfast and before the evening reception.", links: [] },
    { q: "What is the traditional order of speeches?", a: "Father of the bride (or family representative) first, toasting the couple. Groom second, thanking everyone and toasting the bridesmaids. Best man last, responding on behalf of the bridesmaids and roasting the groom. Some couples now have the bride speak too, usually after the groom.", links: [] },
    { q: "Should the groom not see the bride before the ceremony?", a: "Traditionally yes — the groom does not see the bride in her wedding dress until she walks down the aisle. The idea is that the first sight of her in her dress is a shared moment in front of everyone. A first look (seeing each other privately beforehand) is an increasingly popular modern alternative.", links: [] },
    { q: "What is the tradition of carrying the bride over the threshold?", a: "Carrying the new wife over the threshold of your home after the wedding. The origin is disputed — some say it was to prevent the bride from stumbling, which was considered bad luck. It is entirely optional but a fun tradition if you want to do it.", links: [] },
    { q: "Does the groom pay for the first dance song?", a: "No — there is no tradition around who pays for the first dance music. Your band or DJ will cover this as part of their set. Some couples have a specific song recorded or arranged specially, in which case there may be a licensing cost.", links: [] },
    { q: "What is the tradition of the groom not wearing his ring before the wedding?", a: "Some people believe the groom should not wear his wedding ring before the ceremony, as it is meant to be placed on his finger for the first time by his partner. This is a personal choice — there is no universal rule.", links: [] },
    { q: "Is there a tradition around who speaks to the photographer first?", a: "No formal tradition, but it is good practice for the best man to introduce himself to the photographer on arrival and act as the main point of contact for organising group shots. This frees the groom up and keeps things moving.", links: [] },
    { q: "What is the confetti tradition?", a: "Confetti is thrown as the couple leave the ceremony. Traditionally rice was used as a symbol of fertility — confetti replaced it as a more practical alternative. Many venues now restrict or ban confetti for practical reasons, so check with your venue in advance. Biodegradable confetti is widely available and usually permitted.", links: [] },
    { q: "Does the groom give a gift to the bride on the wedding day?", a: "This is not a strict tradition in the UK, but many grooms give a small personal gift — a piece of jewellery, a handwritten letter, or something meaningful. If you do, deliver it before the ceremony via the best man or maid of honour.", links: [] },
  ]},
];

export function FAQModule() {
  const [activeCategory, setActiveCategory] = useState(FAQ_DATA[0].category);
  const [openQuestion, setOpenQuestion] = useState<number | null>(null);
  const activeData = FAQ_DATA.find(c => c.category === activeCategory)!;
  return (
    <div>
      <div style={{ fontSize: 10, fontWeight: 600, letterSpacing: "0.2em", textTransform: "uppercase", color: T.mid, marginBottom: 14 }}>Questions and answers</div>
      <div style={{ fontFamily: "'DM Serif Display', serif", fontSize: 38, color: T.ink, lineHeight: 1.1, marginBottom: 16 }}>Things nobody tells you.</div>
      <div style={{ fontSize: 15, color: T.mid, lineHeight: 1.7, maxWidth: 560, marginBottom: 32 }}>Every question you have been too embarrassed to ask, answered honestly. UK-specific, no fluff.</div>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 32 }}>
        {FAQ_DATA.map(cat => (
          <button key={cat.category} onClick={() => { setActiveCategory(cat.category); setOpenQuestion(null); }}
            style={{ background: activeCategory === cat.category ? T.navy : T.white, color: activeCategory === cat.category ? "white" : T.mid, border: "1px solid " + (activeCategory === cat.category ? T.navy : T.rule), padding: "8px 16px", fontSize: 12, fontWeight: 600, letterSpacing: "0.06em", cursor: "pointer", borderRadius: 2, fontFamily: "Inter, sans-serif" }}>
            {cat.category}
          </button>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 0, border: "1px solid " + T.rule, borderRadius: 4, overflow: "hidden" }}>
        {activeData.questions.map((item, i) => (
          <div key={i} style={{ borderBottom: i < activeData.questions.length - 1 ? "1px solid " + T.rule : "none" }}>
            <button onClick={() => setOpenQuestion(openQuestion === i ? null : i)}
              style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 24px", cursor: "pointer", background: openQuestion === i ? T.navyLight : T.white, transition: "background 0.15s", width: "100%", textAlign: "left", border: "none", fontFamily: "Inter, sans-serif" }}>
              <div style={{ fontFamily: "'DM Serif Display', serif", fontSize: 17, color: T.ink, paddingRight: 16 }}>{item.q}</div>
              <div style={{ fontSize: 18, color: T.mid, flexShrink: 0, transition: "transform 0.2s", transform: openQuestion === i ? "rotate(45deg)" : "rotate(0)", lineHeight: 1 }}>+</div>
            </button>
            {openQuestion === i && (
              <div style={{ padding: "0 24px 20px", background: T.navyLight }}>
                <div style={{ fontSize: 14, color: T.ink, lineHeight: 1.7, marginBottom: item.links.length ? 16 : 0 }}>{item.a}</div>
                {item.links.length > 0 && (
                  <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
                    {item.links.map((link, j) => <AffLink key={j} label={link.label} url={link.url} />)}
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
