import { useState, useEffect } from "react";
import { T } from "../theme";
import { AffLink } from "../shared";

type FAQItem = { q: string; a: string; links: { label: string; url: string }[] };
type FAQCategory = { category: string; questions: FAQItem[] };

const FAQ_DATA: FAQCategory[] = [
  { category: "Wearing it right", questions: [
    { q: "Which buttons do I fasten on a single-breasted two-button jacket?", a: "The top button only. Always. The bottom button on a two-button jacket is never fastened — this is one of the oldest rules in menswear and dates back to King Edward VII. Fastening the bottom button makes the jacket pull, bunch at the waist, and look like it does not fit. When you sit down, unbutton the top button. When you stand, fasten it again.", links: [] },
    { q: "What about a single-breasted three-button jacket?", a: "The middle button always, the top button sometimes, the bottom button never. The most common approach is to fasten only the middle button, which gives a clean line. Some grooms fasten the top and middle together for a more formal look. The bottom button follows the same rule as always — never fastened.", links: [] },
    { q: "What about a single-breasted one-button jacket?", a: "Fasten it when standing, unfasten it when sitting. Simple. A one-button jacket is very clean and modern — the single button sits at the natural waist and the whole line of the jacket depends on it being done up correctly when you are on your feet.", links: [] },
    { q: "How do I wear a double-breasted jacket?", a: "Always fully fastened — both functional buttons done up whenever you are wearing it. Unlike single-breasted, a double-breasted jacket should stay buttoned even when sitting. The overlap of the front panels is structural — an unfastened double-breasted jacket looks deliberately undone rather than casually relaxed. The exception is when you remove it entirely.", links: [] },
    { q: "Does wearing a waistcoat change the button rules?", a: "Yes. When you are wearing a waistcoat, you leave the jacket completely unbuttoned. The waistcoat covers the shirt and waist, so the jacket button serves no functional or visual purpose. Buttoning your jacket over a waistcoat creates bulk and ruins the line of both garments. Jacket open, waistcoat fastened — that is the correct three-piece look.", links: [] },
    { q: "Which buttons do I fasten on a waistcoat?", a: "All of them except the bottom one. The bottom button of a waistcoat is left undone — the same principle as a single-breasted suit jacket. This allows movement, prevents the waistcoat from pulling when you sit, and is simply the correct way to wear one. If your waistcoat has five buttons, fasten the top four. If it has three buttons, fasten the top two.", links: [] },
    { q: "How should a suit jacket fit?", a: "The shoulder seam should sit exactly at the end of your shoulder — not hanging over the arm, not pulling inward. The collar should lie flat against your shirt collar with no gap. The jacket should button without pulling across the chest. The sleeve should show approximately 1–1.5cm of shirt cuff below the jacket sleeve. The jacket length should cover your seat. If any of these are wrong, ask for alterations — most hire companies include basic alterations in the price.", links: [{ label: "Book a fitting at Moss Bros", url: "https://www.mossbros.co.uk/suit-hire" }, { label: "Book at Savoy Taylors Guild", url: "https://www.savoytaylorsguild.co.uk/hire/morning-suits" }] },
    { q: "How much shirt cuff should show below the jacket sleeve?", a: "Approximately 1 to 1.5 centimetres. This is called the shirt cuff break. It is one of the most noticeable details in close-up photographs and at the ceremony. Too much cuff looks like the jacket is too short. No cuff showing looks like the jacket is too long or the shirt is too short. If your cuffs are not showing, ask the hire shop or tailor to shorten the jacket sleeve.", links: [] },
    { q: "How should trousers fit and sit?", a: "Trousers should sit at the natural waist — not on the hips. The break at the hem should be slight, with the trouser just grazing the top of the shoe. Too much break creates a bunching of fabric at the ankle that looks sloppy. No break at all looks very fashion-forward and works with slim modern suits. If you have turn-ups, they add weight to the hem and help it sit correctly.", links: [] },
    { q: "Should I wear a belt or side adjusters?", a: "Side adjusters for formal wear, always. A belt with a formal suit is technically incorrect — belts are workwear and casual wear. A well-fitted suit with side adjusters looks cleaner, sits better, and is simply the more elegant choice. If your trousers only have belt loops, a plain leather belt in black or dark brown is fine, but avoid anything with a prominent buckle.", links: [] },
    { q: "How do I wear a pocket square correctly?", a: "It should look intentional but not overworked. The flat presidential fold — a clean straight edge of fabric just visible above the pocket — works for every suit and every occasion. It takes about 30 seconds to do and never looks wrong. Avoid over-engineered multi-point folds that look like origami. The pocket square should complement the tie or buttonhole, not match it exactly — same colour family, not identical fabric.", links: [] },
    { q: "Should the pocket square match the tie?", a: "No — and this is a common mistake. Matching your pocket square exactly to your tie looks like you bought them as a set, which reads as an effort to coordinate rather than actual style. The pocket square should be in the same colour family or complement the tie without being identical. A classic approach is a white pocket square with any coloured tie — it always works.", links: [] },
    { q: "How do I wear a buttonhole correctly?", a: "The buttonhole goes through the buttonhole on the left lapel — there is a small loop of thread on the back of most jacket lapels specifically for this. The stem should sit vertically and the flower should face outward. Secure it with the pin if provided. It should sit flat against the lapel without drooping. Pick it up on the morning of the wedding, not the day before.", links: [] },
    { q: "When do I take my jacket off?", a: "Traditionally the groom removes his jacket first, giving everyone else permission to do the same. Most grooms keep their jacket on for the ceremony, the drinks reception, and the meal, then remove it for the evening. It is your day — if it is August and 28 degrees, remove it whenever you want. Just do it before everyone else starts quietly dying of heat.", links: [] },
    { q: "How should I tie a half Windsor knot?", a: "The half Windsor produces a medium-sized, neat triangular knot that works with most collar types. Start with the wide end on your right, roughly 30cm lower than the narrow end. Cross the wide end over the narrow end. Bring it up through the neck loop. Wrap it around the front of the narrow end from right to left. Bring it up through the neck loop again. Pass it down through the front loop you just created. Tighten gently and slide up to the collar. The point of the tie should reach your belt buckle.", links: [{ label: "Visual guide on Ties.com", url: "https://www.ties.com/how-to-tie-a-tie/half-windsor" }] },
    { q: "How should I tie a full Windsor knot?", a: "The full Windsor produces a large, wide, symmetrical knot. It requires a spread collar to sit correctly — a narrow collar will look overwhelmed by the knot. Start with the wide end about 40cm lower than the narrow end. Cross wide over narrow. Bring up through neck loop and down to the right. Wrap around the front to the left, then up through the neck loop, then right, then up through the neck loop again. Pass down through the front loop. Tighten and centre. It should fill a spread collar perfectly.", links: [{ label: "Visual guide on Ties.com", url: "https://www.ties.com/how-to-tie-a-tie/windsor" }] },
    { q: "How do I tie a bow tie?", a: "Put the bow tie around your neck with the right side about 3cm longer than the left. Cross the longer end over the shorter end and up through the neck loop — like the first step of tying your shoelaces. Fold the shorter end horizontally to form the front bow shape. Drop the longer end over the centre of this bow. Fold the longer end and push it through the loop behind the front bow. Tighten by pulling both folded ends gently outward. Adjust the symmetry — it should look slightly imperfect, not machine-perfect. Watch a YouTube video the week before, practise twice, and it will take you under a minute on the day.", links: [{ label: "How to tie a bow tie on realmenrealstyle.com", url: "https://www.realmenrealstyle.com/tie-bow-tie/" }] },
    { q: "What is the correct way to wear a cummerbund?", a: "A cummerbund is a wide pleated sash worn around the waist in place of a waistcoat. It covers the trouser waistband and the shirt above it. The single most important rule: pleats face upward. This is one of the most commonly got wrong details in black tie — if the pleats face downward it is immediately noticeable to anyone who knows black tie. The cummerbund should sit snugly at the natural waist, covering the trouser waistband completely. Match it to your bow tie — both in black silk for classic black tie, or both in midnight blue if your tuxedo is midnight blue. Remove it when you remove your jacket.", links: [{ label: "Browse black tie accessories at Hawes and Curtis", url: "https://www.hawesandcurtis.co.uk/mens/black-tie" }] },
    { q: "Should my socks match my trousers or my shoes?", a: "Your trousers. The logic is that socks are a visual extension of the trouser leg — when you cross your legs or walk up stairs, you want the trouser and sock to read as one continuous line down to the shoe. A dark navy suit with dark navy socks and black shoes looks intentional. Dark navy suit with white sports socks is genuinely one of the most common mistakes grooms make on the day.", links: [] },
    { q: "Do I need to break in new shoes before the wedding?", a: "Yes. New leather shoes need wearing in before the day. Wear them around the house for a few evenings and on at least one full day out. Arriving at your ceremony in brand new shoes is a reliable way to spend the entire day in pain. If you are hiring shoes, still worth a short wear beforehand.", links: [{ label: "Browse Loake shoes", url: "https://www.loake.co.uk/collections/oxford-shoes" }] },
    { q: "How do I care for my suit on the morning of the wedding?", a: "Hang it up the night before, never leave it folded. If it has creases, hang it in the bathroom while you shower — steam will relax most of them. If you need to press it, use a pressing cloth between the iron and the fabric to avoid shine marks. Check all buttons are secure. Check the pockets are empty. Put the buttonhole in last, just before you leave.", links: [] },
    { q: "What is the correct way to wear a morning coat?", a: "The morning coat should be left unbuttoned — it is not designed to fasten and attempting to do so looks odd. Wear it with the waistcoat fastened underneath. The coat tails should hang naturally at the back. Trousers should be the matching striped formal pair. It is worn with a tie, not a bow tie — a silk or wool tie in a subtle pattern or plain colour.", links: [{ label: "Hire morning dress at Moss Bros", url: "https://www.mossbros.co.uk/hire" }] },
    { q: "Can I wear suede shoes with a suit?", a: "Yes, with the right suit. Suede works well with lighter and more casual suits — linen, mid-grey, stone, or tan. It reads as more relaxed and contemporary. For a dark formal suit, black tie, or morning dress, polished leather is more appropriate. Brown suede with a navy or grey suit is a classic combination.", links: [{ label: "Browse suede shoes at Loake", url: "https://www.loake.co.uk/collections/suede-shoes" }] },
    { q: "What is the etiquette for wearing a hat to a wedding?", a: "If the dress code specifies it — morning dress or garden party — a top hat is correct. For morning dress, the hat is carried rather than worn indoors, and removed during the ceremony. Outside, it can be worn. For black tie or lounge suit, hats are not part of the dress code, though a Panama or flat cap can work at summer outdoor weddings with more relaxed dress codes.", links: [] },
  ]},
  { category: "Attire", questions: [
    { q: "Do my groomsmen have to match?", a: "No. Coordinated is fine — same colour with slight variations in lapel or neckwear is more interesting than identical suits. The most common approach is same suit, different tie on the groom, which makes you stand out without anyone looking wrong.", links: [] },
    { q: "Who pays for the groomsmen suits?", a: "Traditionally the groom pays for groomsmen hire. If you are asking them to hire specifically for your wedding, covering the cost is a genuine gesture and increasingly expected. Many grooms ask groomsmen to buy their own if purchasing to keep — especially if the suit is a style they will wear again.", links: [{ label: "Hire at Moss Bros", url: "https://www.mossbros.co.uk/hire" }] },
    { q: "How far in advance should I book a suit hire?", a: "At least 3–4 months. Six months is better for a large party. Fittings typically happen 6–8 weeks out with collection a week before. Do not leave it later than 6 weeks or you risk limited stock in your size.", links: [{ label: "Book at Moss Bros", url: "https://www.mossbros.co.uk/hire" }, { label: "Book at Savoy Taylors Guild", url: "https://www.savoytaylorsguild.co.uk/hire/morning-suits" }] },
    { q: "What is the difference between a notched and a peak lapel?", a: "A notched lapel has a small V-shaped cutout where the collar meets the lapel — the most common style on suits. A peak lapel has points that angle upward toward the shoulders, giving a more formal and assertive look. Most grooms choose peak to stand out from their groomsmen. Shawl lapels are a continuous curve — classic on a tuxedo.", links: [] },
    { q: "Should my shoes match my groomsmen?", a: "They do not need to match exactly, but should be in the same family — similar formality level and colour tone. Black Oxfords match anything dark and formal. Brown or tan works with lighter or more relaxed suits.", links: [{ label: "Shop at Loake", url: "https://www.loake.co.uk/collections/oxford-shoes" }, { label: "Shop at Cheaney", url: "https://www.cheaney.co.uk/collections/mens-oxford-shoes" }] },
    { q: "Do I need a buttonhole?", a: "Not strictly, but they are worth having. A buttonhole costs around £10–15 from your florist, coordinates with the bouquet, and genuinely elevates the look in photographs. Your florist will provide one as standard for the groom — ask about groomsmen buttonholes at the same time.", links: [] },
    { q: "What is the difference between pocket styles?", a: "Flap pockets have a fabric flap over the opening — the standard casual style. Jetted pockets have no flap, just a clean slit, and are more formal — correct for black tie. Patch pockets are visible stitched pockets sewn onto the outside of the jacket, more casual and common on linen or summer suits. A ticket pocket is a small extra pocket above the right hip pocket — a very British detail.", links: [] },
    { q: "What colour suit works best for an outdoor summer wedding?", a: "Lighter greys, mid-blue, stone, or linen-toned suits work well in summer light. Avoid heavy charcoal or black — they absorb heat and look oppressive in bright outdoor photos. Navy is the most versatile choice across all seasons and lighting conditions.", links: [{ label: "Browse at Charles Tyrwhitt", url: "https://www.ctshirts.com/suits?colour=navy" }] },
    { q: "Should I buy or hire?", a: "Hire if you are unlikely to wear a formal suit again. Buy if you wear suits for work or events regularly, or if the style is one you will reach for again. A good off-the-peg suit from Next, Ted Baker, or Reiss at £300–500 is often better value than repeated hire, and fits better after tailoring.", links: [{ label: "Browse at Next", url: "https://www.next.co.uk/shop/gender-men/category-suits" }, { label: "Browse at Ted Baker", url: "https://www.tedbaker.com/uk/mens/category/suits" }] },
    { q: "What is the difference between a tuxedo and a dinner jacket?", a: "The same thing. A dinner jacket is the British term; tuxedo is American. Both refer to a formal evening jacket with silk or satin lapels worn for black tie occasions. The jacket is typically paired with matching trousers with a silk seam stripe down the leg.", links: [] },
    { q: "Is it acceptable to wear a coloured suit to my own wedding?", a: "Absolutely. Burgundy, forest green, and camel are all increasingly common choices. The key is that the dress code and venue should support it — a bold colour suit at a formal black tie wedding looks wrong, but at a country house or barn wedding it can be genuinely exceptional. Have the confidence to carry it.", links: [{ label: "Browse at ASOS", url: "https://www.asos.com/men/suits/cat/?cid=3636" }] },
    { q: "What is the correct shirt for a tuxedo?", a: "A white dress shirt with a stiff bib front — either a pleated bib or marcella (piqué fabric). It should have a wing collar for very formal black tie, or a turn-down collar for a more modern look. Double cuffs requiring cufflinks are standard. Do not wear a standard business shirt with a tuxedo — the collar and front will look wrong.", links: [{ label: "Browse at Hawes and Curtis", url: "https://www.hawesandcurtis.co.uk/mens/formal-shirts" }] },
    { q: "How do I avoid looking like I hired my suit?", a: "Fit is everything. A well-fitted hire suit looks as good as anything off a rack. Make sure the shoulders sit correctly, the jacket sleeves are the right length, and the trousers have a clean break. Ask for alterations — most hire companies include basic alterations. Shoes and accessories matter more than most grooms realise.", links: [] },
    { q: "What is the difference between highland dress and a kilt outfit?", a: "Highland dress is a formal ensemble: Prince Charlie jacket, waistcoat, kilt, formal sporran, kilt hose, and ghillie brogues. It is correct for Scottish weddings and Highland-themed events. A more casual kilt outfit might use an Argyll jacket instead of Prince Charlie — less formal and more commonly hired. If the wedding is formal, Prince Charlie is correct.", links: [] },
  ]},
  { category: "Rings", questions: [
    { q: "Do I actually need to wear a wedding ring?", a: "No. It is a personal choice. Some grooms do not wear jewellery, have jobs where rings are impractical or dangerous, or simply prefer not to. Worth a frank conversation with your partner beforehand.", links: [] },
    { q: "Who buys the groom's wedding ring?", a: "Traditionally the bride's family bought the groom's ring and the groom's family bought the bride's. In practice, most couples simply buy both rings together from the same jeweller — often at a small combined discount.", links: [] },
    { q: "Should my ring match her engagement ring?", a: "Worth thinking about carefully. If her engagement ring is platinum or white gold, yellow gold on your finger will create a contrast. Some couples love this; others find it jarring in photographs. White gold, platinum, or palladium on the groom's hand will complement any white metal engagement ring.", links: [{ label: "Browse at Beaverbrooks", url: "https://www.beaverbrooks.co.uk/mens/wedding-rings" }] },
    { q: "Can I get my ring resized after the wedding?", a: "Most metals can be resized. Gold and platinum resize relatively easily at most jewellers. Tungsten, titanium, carbon fibre, and silicone cannot be resized at all — if your finger changes size, you need a new ring. If you are considering these materials, size carefully.", links: [] },
    { q: "What is the difference between platinum and white gold?", a: "Platinum is naturally white and stays white permanently — it never needs replating. White gold is yellow gold coated in rhodium, which wears off over time. Rhodium replating costs £40–80 every 2–5 years depending on wear. Platinum is heavier and more expensive but genuinely maintenance-free.", links: [] },
    { q: "What is the difference between 9ct and 18ct gold?", a: "The number refers to purity. 18ct gold is 75% pure gold — richer in colour, slightly softer, and more prestigious. 9ct gold is 37.5% pure — paler in colour, more durable because of the higher alloy content, and significantly cheaper. Both are genuine gold rings. 18ct looks better; 9ct is more practical if you work with your hands.", links: [] },
    { q: "Does a hammered finish hide scratches?", a: "Yes, significantly. A hammered or matte finish masks everyday wear far better than a polished mirror finish. If you work with your hands or are hard on jewellery, matte or hammered is a practical as well as a stylistic choice.", links: [{ label: "Browse hammered rings on Etsy UK", url: "https://www.etsy.com/uk/search?q=hammered+mens+wedding+ring" }] },
    { q: "How do I measure my ring size at home?", a: "Wrap a thin strip of paper around the base of your ring finger (not the knuckle), mark where it overlaps, measure the length in millimetres, and divide by 3.14 to get the diameter in mm. Any jeweller can then match this to a UK ring size. Fingers swell in heat and shrink in cold — measure at room temperature and at the end of the day for the most accurate size.", links: [{ label: "F.Hinds ring size guide", url: "https://www.fhinds.co.uk/help/ring-size-guide" }] },
    { q: "What is a silicone ring and who is it for?", a: "A soft, flexible ring made from silicone. Popular with grooms in healthcare, construction, manual trades, and sport — jobs where a metal ring is impractical or dangerous. Cannot catch on machinery. Many grooms buy a silicone ring for work and a metal ring for everyday and formal wear.", links: [{ label: "Browse on Amazon UK", url: "https://www.amazon.co.uk/s?k=silicone+wedding+ring+mens" }] },
    { q: "What about a ring tattoo?", a: "A permanent design inked on the ring finger. Zero ongoing cost, impossible to lose, completely personal. The design can be anything from a simple black band to an intricate pattern. Research your artist carefully — quality varies enormously and this is permanent. A simple band tattoo typically costs £40–80.", links: [{ label: "Find artists on Tattoodo", url: "https://www.tattoodo.com/find?type=tattoo&q=ring+tattoo" }] },
    { q: "Is palladium worth considering?", a: "Yes — it is underrated. Palladium is naturally white like platinum, lighter than platinum, and does not need rhodium replating like white gold. It typically costs less than platinum. The main drawback is that fewer high-street jewellers stock it, so your options are slightly more limited.", links: [{ label: "Browse palladium rings at Steven Stone", url: "https://www.stevenstone.co.uk/mens-wedding-rings" }] },
    { q: "What width should my wedding ring be?", a: "Most men wear between 4mm and 6mm. Narrower (3–4mm) looks more delicate and suits slimmer fingers. Wider (6–8mm) makes more of a statement and suits larger hands. The best approach is to try several widths in person — most jewellers will show you multiple widths side by side, and it makes the choice obvious.", links: [] },
    { q: "Should I buy from a high street jeweller or an independent?", a: "Both have advantages. High street chains like Beaverbrooks, Ernest Jones, and F.Hinds offer consistency, clear pricing, and nationwide service. Independent jewellers often offer better craftsmanship, more unusual materials, and bespoke engraving. For standard gold or platinum bands, the high street is reliable. For meteorite inlays, fingerprint engraving, or unusual materials, seek out a specialist independent.", links: [{ label: "Browse at Beaverbrooks", url: "https://www.beaverbrooks.co.uk/mens/wedding-rings" }, { label: "Browse independents on Etsy UK", url: "https://www.etsy.com/uk/search?q=mens+wedding+ring" }] },
    { q: "Can I wear my wedding ring during sport or at the gym?", a: "It depends on the material. Gold and platinum are soft enough to scratch and warp under pressure — most jewellers recommend removing them for contact sport. Tungsten and titanium are far more durable. Silicone is designed specifically for active wear. If you are active, consider a silicone secondary ring for training.", links: [] },
    { q: "How much should I spend on a wedding ring?", a: "Whatever suits your budget. There is no minimum. A quality sterling silver ring from a good independent costs £30–60 and will last decades with care. A platinum ring from a specialist jeweller runs to £600–1,800. Most grooms spend £200–500. The ring's meaning has nothing to do with its price.", links: [] },
  ]},
  { category: "Stag", questions: [
    { q: "Who organises the stag do?", a: "The best man, traditionally. He plans it, coordinates the group, collects deposits, and manages all the details. The groom's job is to show up. If the best man is not well-organised, a capable groomsman should step in rather than let the planning drift.", links: [] },
    { q: "Who pays for the stag do?", a: "Each person pays their own way, including the groom in most cases. Traditionally the group covered the groom's share, but this is less universal now — particularly for longer or more expensive trips. If the group wants to cover the groom, agree it explicitly before booking.", links: [] },
    { q: "How far in advance should I book?", a: "At least 3–4 months for UK trips, 4–6 months for European travel. Popular destinations like Krakow and Budapest have packages that sell out during peak months. The bigger the group, the earlier you need to start — getting 12 people to agree on dates alone can take a month.", links: [{ label: "Search flights on Skyscanner", url: "https://www.skyscanner.net/flights/gb/anywhere/" }] },
    { q: "What if someone in the group cannot afford it?", a: "Either choose a destination and budget that genuinely works for everyone, or have a frank private conversation with that person early. Do not put social pressure on people to spend money they do not have. The best stag dos are rarely the most expensive ones.", links: [] },
    { q: "Should I invite my dad to the stag?", a: "Only if he would genuinely enjoy it and fit into the group dynamic. A split stag — lunch or an afternoon activity with family, then a separate evening with the core group — is increasingly common and works well when ages or interests diverge significantly.", links: [] },
    { q: "Is Krakow still worth it?", a: "Yes. It remains the best value European stag destination. Flights are short and cheap, accommodation is excellent value, nightlife is welcoming to British groups, and there is genuinely more to do than just drinking — Auschwitz, the salt mines, the castle, rafting on the Dunajec.", links: [{ label: "Flights to Krakow on Skyscanner", url: "https://www.skyscanner.net/flights/gb/kra/" }] },
    { q: "Is Budapest worth it?", a: "Absolutely. Budapest has overtaken Krakow as the most-recommended European stag destination among UK groups in 2024–25. Ruin bars, thermal baths, boat parties, and some of the most visually spectacular nightlife in Europe. Slightly pricier than Krakow but still excellent value.", links: [{ label: "Flights to Budapest on Skyscanner", url: "https://www.skyscanner.net/flights/gb/bud/" }] },
    { q: "Do I need travel insurance for a European stag?", a: "Yes, without question. A standard single-trip policy costs around £10–20 per person and covers medical emergencies, cancellations, and lost luggage. The most common stag claim is cancelled or missed flights due to someone in the group being refused boarding. Buy it the moment you book.", links: [{ label: "Compare on Compare the Market", url: "https://www.comparethemarket.com/travel-insurance/single-trip/" }] },
    { q: "What if someone drops out after paying?", a: "Anyone who drops out should still contribute to fixed costs — accommodation and activities that were booked on their behalf. The best man should collect deposits before booking anything and make this policy clear upfront. It prevents awkwardness later.", links: [] },
    { q: "What is the best UK stag destination?", a: "Newcastle is consistently rated the best value and most stag-friendly UK city — more bars per square mile than anywhere else, £4–5 pints, and legendary northern hospitality. Edinburgh is the best all-rounder. Bristol, Liverpool, and Cardiff are strong alternatives. The Lake District, Scottish Highlands, and Welsh countryside work well for activity-based stags.", links: [] },
    { q: "How do I handle a group that cannot agree on a destination?", a: "The best man should shortlist two or three realistic options based on budget and interests, then run a simple group vote. Decisions made by committee with unlimited options never get made. Present the choices, set a deadline, move on.", links: [] },
    { q: "What activities work for mixed groups?", a: "Clay pigeon shooting, go-karting, escape rooms, and golf all work well across a wide range of ages and fitness levels. Avoid anything that requires high physical fitness unless you know the group well. A good evening meal before the night out is underrated — it sets the tone and ensures everyone is in a reasonable state.", links: [] },
    { q: "What should I actually do in Benidorm?", a: "Benidorm divides opinion, but it delivers exactly what it promises: cheap drinks, a strip designed for British stag groups, and guaranteed sunshine. The Levante Beach strip is the hub. Book a daytime activity — quad biking or a boat trip — before the evening. Manage expectations and it will be good fun.", links: [{ label: "Flights to Alicante on Skyscanner", url: "https://www.skyscanner.net/flights/gb/alc/" }] },
    { q: "What should I pack for a stag weekend?", a: "Whatever the itinerary requires, plus: a photocopy of your passport, travel insurance documents, any prescription medication, a portable phone charger, and enough cash for the first night. Do not bring anything you would be devastated to lose. Leave valuables at home.", links: [] },
    { q: "Is a hiring a house for a stag do worth it?", a: "For the right group, absolutely. A hired house in the Cotswolds, Lake District, or Scottish Highlands costs roughly the same per head as a hotel in a city but gives you a private space, a kitchen, a garden, and no checkout pressure. Works best for groups that want to do activities rather than nightlife.", links: [] },
  ]},
  { category: "Speech", questions: [
    { q: "When does the groom give his speech?", a: "At a UK wedding, the traditional order is: father of the bride (or a family representative) first, groom second, best man last. Some couples now include the bride, who typically speaks after the groom or at the end.", links: [] },
    { q: "How long should the groom's speech be?", a: "4–5 minutes is ideal. At a comfortable speaking pace of about 130 words per minute, that is 520–650 words. Most grooms write too much and rush — cut ruthlessly. A tight 4-minute speech that lands is far better than 8 minutes of wandering.", links: [] },
    { q: "Can I use notes?", a: "Yes, and you should. A small card or two is perfectly normal and most guests will never notice. If you use your phone, keep the screen brightness high and notifications off. Do not try to memorise the whole speech word-for-word — if you lose your place you will panic. Know the structure and key lines; glance at notes for the rest.", links: [] },
    { q: "What should I actually say about my wife?", a: "One specific story or moment that shows who she is — not a list of qualities. The moment you knew she was the one, the thing she did that made you think you had never met anyone like this. Specific is always more powerful than general. Guests remember the story; they forget the adjectives.", links: [] },
    { q: "How do I deal with nerves before the speech?", a: "Practise out loud until you know the structure well enough to look up regularly. Eat something before the meal. One or two drinks is fine; more significantly impairs performance, however confident it feels. Accept that nerves are invisible from the room — audiences want you to succeed and forgive far more than you imagine.", links: [] },
    { q: "Should I mention ex-partners in the speech?", a: "No. There is no version of this that works.", links: [] },
    { q: "Do I have to thank everyone?", a: "You should thank both sets of parents, your partner, and the groomsmen. Beyond that is optional. Avoid reading out a long list of names — guests disengage immediately. If you want to acknowledge specific people, weave them into the speech naturally rather than listing them.", links: [] },
    { q: "What is the order of toasts?", a: "The groom traditionally toasts the bridesmaids at the end of his speech. The best man then responds on behalf of the bridesmaids and proposes the final toast to the couple. The father of the bride typically opens the speeches by toasting the couple.", links: [] },
    { q: "Should the speech be funny?", a: "Not necessarily. A warm, honest, well-delivered speech without a single joke is far better than a speech full of jokes that fall flat. If you are naturally funny, let it show. If you are not, lean into sincerity — it is more affecting than forced humour and guests respond to it.", links: [] },
    { q: "How personal should I get?", a: "As personal as you are comfortable with. The most memorable groom's speeches tend to have one moment of genuine emotion — a real story, a true feeling, something unguarded. You do not have to cry. But the attempt at honesty is what people remember long after the speech is over.", links: [] },
    { q: "How do I handle it if I start to cry?", a: "Pause. Breathe. Take a sip of water. The room will be with you — crying at a wedding speech is not weakness, it is sincerity, and most guests will find it moving rather than awkward. The worst thing you can do is rush through emotional material to get past it.", links: [] },
    { q: "Should I rehearse the speech in front of someone?", a: "Yes, ideally more than once, and ideally in front of people whose opinion you trust. Hearing your own speech out loud for the first time in front of 80 people is not the right time to discover the third story runs too long. Your best man, a parent, or a close friend will give you useful feedback.", links: [] },
    { q: "What if the best man's speech is offensive or goes on too long?", a: "Talk to him beforehand. A brief, direct conversation — 'keep it under 7 minutes, nothing about X or Y' — is entirely reasonable and most best men will welcome the guidance. You are not censoring him; you are protecting everyone's experience including his.", links: [] },
  ]},
  { category: "On the day", questions: [
    { q: "What time should I arrive at the venue?", a: "At least 45 minutes before the ceremony start time. This gives you time to greet arriving guests, sort any last-minute details with the venue, check the room, and settle your nerves. Being there early also means guests do not arrive before you, which is awkward for everyone.", links: [] },
    { q: "What do I do on the morning of the wedding?", a: "Eat a proper breakfast — you may not eat again until the wedding breakfast several hours later. Have a clear plan for getting ready with your groomsmen. Confirm timings with the best man the night before. Leave more time than you think you need. Do not attempt anything new on the morning of the wedding.", links: [] },
    { q: "Should I eat before the ceremony?", a: "Yes. Definitely. Nerves combined with an empty stomach and standing in a warm room for 45 minutes is a reliable recipe for feeling unwell. Eat a proper breakfast and drink enough water. Do not start drinking alcohol on an empty stomach.", links: [] },
    { q: "Can I see my partner before the ceremony?", a: "Traditionally no — the groom does not see the bride in her wedding dress until she walks down the aisle. A first look — a private moment together before the ceremony — is increasingly popular and often produces more relaxed and natural photographs. Discuss it with your partner and photographer.", links: [] },
    { q: "How much cash should I have on the day?", a: "Enough to cover supplier gratuities if you are giving them. Work out who you want to tip, put cash in named envelopes, and give them to the best man to distribute at the right moments. Do not carry large amounts of cash yourself during the day.", links: [] },
    { q: "What do I do during the couple portraits?", a: "This is your only window to eat, drink something decent, and decompress between the ceremony and the reception. Do not let your photographer rush through it. Have a drink, eat from the canapé spread, see your family. The portraits can take 30–60 minutes — that is time you should be using.", links: [] },
    { q: "How do I stay calm at the ceremony?", a: "Arrive early. Talk to guests as they arrive — it gives you something to do and settles nerves faster than standing still. Breathe slowly and deliberately when you are waiting. The moment you see your partner, everything else disappears anyway.", links: [] },
    { q: "What if something goes wrong on the day?", a: "It will. Something always does. The flowers arrive wrong, the buttonholes are misdelivered, someone gets stuck in traffic. The best man's job is to manage these problems without telling you about them. Delegate everything to him and your wedding coordinator. Your only job is to be present and enjoy the day.", links: [] },
    { q: "When should I stop drinking at the reception?", a: "There is no rule, but the groom tends to be the most-photographed person at a wedding. Most grooms drink more slowly than they planned to in the weeks beforehand and genuinely appreciate it later. Drink enough to relax. Drink less than you would at someone else's wedding.", links: [] },
    { q: "How do I make sure I actually enjoy the day?", a: "Set clear expectations with your partner about which moments matter most to you — the ceremony, the meal, the first dance. Let go of everything else. Assign one trusted person to handle logistics. Eat breakfast. Take 10 minutes alone with your new spouse early in the evening before the room fills up. That is the moment most grooms say they wish had lasted longer.", links: [] },
  ]},
  { category: "Money & etiquette", questions: [
    { q: "Who pays for what at a UK wedding traditionally?", a: "Traditionally the bride's family paid for most of the wedding; the groom paid for the honeymoon, rings, and wedding cars. In practice most modern couples split costs between themselves and contributions from both families based on means and preference, not tradition.", links: [] },
    { q: "Do I need to tip wedding suppliers in the UK?", a: "Tipping is not expected in the UK the way it is in the US, but it is a genuinely appreciated gesture for good service. It is entirely optional. Cash in envelopes given to the relevant person at the end of the day is the standard approach — give them to the best man to distribute so you can focus on the evening.", links: [] },
    { q: "How much should I tip the photographer?", a: "There is no set amount. If you want to tip, £50–100 for a solo photographer or £100–200 for a two-person team is generous and widely appreciated. Photographers often work 10–14 hour days at weddings.", links: [] },
    { q: "How much should I tip the band or DJ?", a: "Optional. £50–100 for a DJ, £100–200 for a band is typical if you want to show appreciation. The decision to tip should be based on how the day went, not obligation.", links: [] },
    { q: "Should I give my groomsmen a gift?", a: "It is a nice gesture and most grooms do. Something personal and practical lands better than generic engraved hip flasks. Consider what each person actually likes rather than a one-size solution.", links: [{ label: "Browse at Not On The High Street", url: "https://www.notonthehighstreet.com/personalisedgifts/for-him" }, { label: "Browse personalised gifts at Etsy UK", url: "https://www.etsy.com/uk" }] },
    { q: "What is an appropriate groomsmen gift budget?", a: "£30–75 per groomsman is typical. More for a best man who has put in significant work. Quality matters more than price — a £40 gift that is exactly right is better than an £80 gift that is generic.", links: [] },
    { q: "Should I write personal thank you cards?", a: "Yes. Handwritten cards to parents, bridal party, and close friends who contributed meaningfully are genuinely appreciated and increasingly rare. Aim to send them within 3 weeks of the wedding while the detail is still fresh.", links: [{ label: "Browse cards at Papier", url: "https://www.papier.com/thank-you-cards" }] },
    { q: "What is a wedding gift list and do I need one?", a: "A gift list (or registry) lets guests choose a gift you actually want, avoids duplicates, and takes the awkwardness out of giving. Most couples use one. John Lewis, Amazon, and Prezola are the most common UK providers. A cash fund or honeymoon contributions are also widely accepted now.", links: [{ label: "Set up a list at John Lewis", url: "https://www.johnlewis.com/wedding-list" }, { label: "Browse at Prezola", url: "https://www.prezola.com" }] },
    { q: "Is it acceptable to have a no-children wedding?", a: "Yes — it is your wedding and a no-children policy is widely accepted. Be clear and consistent — if you are making exceptions for close family, that is fine, but make sure guests know early. The invitation wording should be explicit rather than leaving people to guess.", links: [] },
    { q: "How do I handle a family member who is upset about not being included in the wedding party?", a: "A direct, private, and honest conversation is better than avoidance. Acknowledge their feelings, explain your decision without over-justifying it, and find another meaningful role if possible — reading at the ceremony, helping with logistics on the day. Most people understand when spoken to directly and early.", links: [] },
  ]},
  { category: "Honeymoon", questions: [
    { q: "Who plans the honeymoon?", a: "Traditionally the groom planned and paid for the honeymoon as a surprise. In practice most couples plan it together, which avoids the risk of a surprise honeymoon that does not match your partner's preferences. A surprise destination is still possible while involving your partner in the timing and style.", links: [{ label: "Browse packages on Kuoni", url: "https://www.kuoni.co.uk/honeymoons" }, { label: "Browse on Mr and Mrs Smith", url: "https://www.mrandmrssmith.com/romantic-hotels" }] },
    { q: "How soon after the wedding should the honeymoon be?", a: "Most couples travel within a week of the wedding. Some take a short mini-moon immediately and a longer trip later — particularly if a major destination requires significant planning or if the wedding is in peak season. There is no correct answer.", links: [] },
    { q: "Do I need to change my name on my passport before the honeymoon?", a: "If your partner is changing her name, all travel bookings must match her current passport name — not her new name. Do not book in a new name until you have the new passport. It is simpler and cheaper to book travel in her maiden name and change the passport afterwards.", links: [] },
    { q: "Should I tell the hotel it is our honeymoon?", a: "Yes. Most hotels will acknowledge it in some way — room upgrade, champagne on arrival, flowers, or a note. Mention it when booking and again at check-in. There is no downside to telling them.", links: [] },
    { q: "What is a mini-moon?", a: "A short honeymoon — typically 3–5 nights, often somewhere in the UK or within a 2-hour flight — taken immediately after the wedding, sometimes before a longer trip later. The UK has excellent options: the Cotswolds, Scottish Highlands, Lake District, and coastal Cornwall are all popular mini-moon destinations.", links: [{ label: "Browse UK hotels on Mr and Mrs Smith", url: "https://www.mrandmrssmith.com/romantic-hotels/england" }] },
    { q: "When should I book the honeymoon?", a: "As soon as the wedding date is confirmed, ideally 9–12 months ahead for popular destinations and peak seasons. Popular Maldives, Seychelles, and Amalfi Coast properties fill up fast. Last-minute honeymoon deals exist but the risk of limited availability is real.", links: [] },
    { q: "Do I need vaccinations for a honeymoon abroad?", a: "Depends entirely on the destination. For Southeast Asia, Africa, South America, and some Caribbean islands, vaccinations and anti-malarial medication may be required or strongly recommended. Check the NHS Travel Health pages and allow 6–8 weeks before travel for any course of injections.", links: [{ label: "Check requirements on NHS Travel Health", url: "https://travelhealthpro.org.uk" }] },
  ]},
  { category: "Traditions", questions: [
    { q: "Do the groom and best man greet guests on arrival?", a: "Traditionally yes — the groom and groomsmen welcome arriving guests before the ceremony. It is a warm gesture and gives you something useful to do while waiting. It is not a strict requirement but almost universally appreciated by guests.", links: [] },
    { q: "Does the suit jacket stay on until the groom removes his?", a: "Yes — by convention the groom removes his jacket first, signalling that everyone else may do the same. Most grooms remove theirs after the wedding breakfast and before the evening reception. It is a small gesture that is noticed and appreciated.", links: [] },
    { q: "What is the traditional order of speeches?", a: "Father of the bride (or family representative) first, toasting the couple. Groom second, thanking everyone and toasting the bridesmaids. Best man last, responding on behalf of the bridesmaids and roasting the groom. Some modern weddings include the bride, who typically speaks after the groom.", links: [] },
    { q: "Should the groom not see the bride before the ceremony?", a: "Traditionally no. The idea is that the first sight of her in her dress is a shared public moment at the ceremony. A first look — seeing each other privately beforehand — is a popular modern alternative that often produces more relaxed photographs. Neither approach is wrong.", links: [] },
    { q: "What is the tradition of carrying the bride over the threshold?", a: "Carrying the new wife over the threshold of your home after the wedding. The origin is disputed. It is entirely optional but a genuinely fun tradition if you want to do it — and one of the few moments of the day that happens in private.", links: [] },
    { q: "Does the groom pay for the first dance song?", a: "There is no tradition around this. Your band or DJ will cover the first dance as part of their set. If you want a specific live arrangement of a song that is not in their repertoire, some bands charge extra to learn it — worth discussing in advance.", links: [] },
    { q: "What is the tradition of the groom not wearing his ring before the wedding?", a: "Some people hold that the ring should be placed on the groom's finger for the first time by his partner at the ceremony. It is a personal choice — there is no universal rule and many grooms wear their ring beforehand to check the fit.", links: [] },
    { q: "What is the confetti tradition?", a: "Confetti is thrown as the couple leave the ceremony — traditionally rice, replaced by paper confetti as a more practical alternative. Many venues now restrict or ban confetti for practical reasons; always check in advance. Biodegradable petal confetti is widely available and usually permitted where paper is not.", links: [] },
    { q: "Does the groom give a gift to the bride on the wedding day?", a: "Not a strict UK tradition, but a growing number of grooms do — a piece of jewellery, a handwritten letter, or something personally meaningful. If you do, deliver it before the ceremony via the best man or maid of honour so she can read it privately.", links: [] },
    { q: "What is a something old, something new, something borrowed, something blue?", a: "A traditional wedding rhyme for the bride, not the groom. Each item brings a different type of luck. Something old connects to the past, something new to the future, something borrowed brings luck from a happily-married friend or relative, and something blue symbolises fidelity. The groom has no equivalent tradition, though some grooms borrow the concept for their own cufflinks or a small keepsake.", links: [] },
    { q: "Why does the best man stand on the groom's right?", a: "The tradition dates to when grooms sometimes had to defend their right to marry — the best man stood to the groom's right to keep his sword arm free. The role itself derives from Anglo-Saxon 'best man' meaning the most capable fighter available to defend the marriage. Most modern best men are selected on slightly different criteria.", links: [] },
  ]},
];

export function FAQModule() {
  // FAQPage structured data, generated from the real content above so it
  // never drifts. Helps search engines understand the page; rich-result
  // display is at Google's discretion.
  useEffect(() => {
    const data = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": FAQ_DATA.flatMap(c => c.questions).map(q => ({
        "@type": "Question",
        "name": q.q,
        "acceptedAnswer": { "@type": "Answer", "text": q.a },
      })),
    };
    const s = document.createElement("script");
    s.type = "application/ld+json";
    s.id = "faq-jsonld";
    s.textContent = JSON.stringify(data);
    document.head.appendChild(s);
    return () => { document.getElementById("faq-jsonld")?.remove(); };
  }, []);

  const [activeCategory, setActiveCategory] = useState(FAQ_DATA[0].category);
  const [openQuestion, setOpenQuestion] = useState<number | null>(null);
  const activeData = FAQ_DATA.find(c => c.category === activeCategory)!;
  return (
    <div>
      <div style={{ fontFamily: "'DM Serif Display', serif", fontSize: 42, color: T.ink, lineHeight: 1.08, marginBottom: 14, letterSpacing: "-0.01em" }}>Things nobody tells you.</div>
      <div style={{ fontSize: 15, color: T.mid, lineHeight: 1.7, maxWidth: 560, marginBottom: 28 }}>Every question you were too embarrassed to ask, answered honestly. UK-specific.</div>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 32 }}>
        {FAQ_DATA.map(cat => (
          <button key={cat.category} onClick={() => { setActiveCategory(cat.category); setOpenQuestion(null); }}
            style={{ background: activeCategory === cat.category ? T.navy : T.white, color: activeCategory === cat.category ? "white" : T.mid, border: "1px solid " + (activeCategory === cat.category ? T.navy : T.rule), padding: "8px 16px", fontSize: 12, fontWeight: 600, letterSpacing: "0.06em", cursor: "pointer", borderRadius: 2, fontFamily: "Inter, sans-serif" }}>
            {cat.category}
          </button>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 0, border: "1px solid " + T.rule, borderRadius: 4, overflow: "hidden" }}>
        {activeData.questions.map((item, i) => (
          <div key={i} style={{ borderBottom: i < activeData.questions.length - 1 ? "1px solid " + T.rule : "none" }}>
            <button onClick={() => setOpenQuestion(openQuestion === i ? null : i)}
              style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 24px", cursor: "pointer", background: openQuestion === i ? T.navyLight : T.white, transition: "background 0.15s", width: "100%", textAlign: "left", border: "none", fontFamily: "Inter, sans-serif" }}>
              <div style={{ fontFamily: "'DM Serif Display', serif", fontSize: 17, color: T.ink, paddingRight: 16 }}>{item.q}</div>
              <div style={{ fontSize: 18, color: T.mid, flexShrink: 0, transition: "transform 0.2s", transform: openQuestion === i ? "rotate(45deg)" : "rotate(0)", lineHeight: 1 }}>+</div>
            </button>
            {openQuestion === i && (
              <div style={{ padding: "0 24px 20px", background: T.navyLight }}>
                <div style={{ fontSize: 14, color: T.ink, lineHeight: 1.7, marginBottom: item.links.length ? 16 : 0 }}>{item.a}</div>
                {item.links.length > 0 && (
                  <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
                    {item.links.map((link, j) => <AffLink key={j} label={link.label} url={link.url} />)}
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
